[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'ecco_production'
version = '1.0'
dependencies = [
    'boto3',
    'cartopy',
    'matplotlib',
    'netCDF4',
    'numpy',
    'pyresample',
    'scipy',
    'xarray',
    'xmitgcm',
    'xgcm',
    'ecco_cloud_utils @ git+https://github.com/ECCO-GROUP/ECCO-ACCESS/#subdirectory=ecco-cloud-utils',
]

[tool.setuptools]
packages=[
    'ecco_production',
]

[tool.setuptools.package-dir]
ecco_production     = 'src/ecco_production'

[project.scripts]
ecco_production     = 'ecco_production.bin.master_script:main'
ep_aws_s3_sync      = 'ecco_production.bin.aws_s3_sync:main'
ep_create_factors   = 'ecco_production.bin.create_factors:main'

