# =================================================================================================
# Metadata, Filenames, and Paths
# =================================================================================================
# Boolean
# Controls whether or not to create a checksum for each produced dataset
create_checksum: True

# Boolean
# Controls whether or not to download all field files at the same time for each time level instead
# of one at a time. Setting to true makes downloading quicker, but use more memory and disk space.
download_all_fields: True

# Boolean
# Controls whether or not to download the uploaded dataset file and compare it's checksum to the
# the dataset file before it was uploaded to S3
compare_checksums: True

# Boolean
# Controls whether or not to download files in parallel for the timestep being processed
use_workers_to_download: True

# String
# Output dataset DOI (as from PODAAC_datasets metadata file)
doi: '10.5067'

# String
# Version number of ECCO output
ecco_version: 'V4r4'

# String
# Name of processing code file to import. Assumes it has a function named "generate_netcdfs" which
# accepts the payload defined in master_script.py
processing_code_filename: 'eccov4r4_gen_for_podaac_cloud'

# Boolean
# Include extra print statements when processing
extra_prints: False

# String
# Tail string for the dataset description for latlon grid
dataset_description_tail_latlon: ' interpolated to a regular 0.5-degree grid from the ECCO Version 4 revision 4 (V4r4) ocean and sea-ice state estimate.'

# String
# Tail string for the dataset description for native grid
dataset_description_tail_native: ' on the native Lat-Lon-Cap 90 (LLC90) model grid from the ECCO Version 4 revision 4 (V4r4) ocean and sea-ice state estimate.'

# String
# Tail string for filename of processed files for latlon grid
filename_tail_latlon: '_ECCO_V4r4_latlon_0p50deg.nc'

# String
# Tail string for filename of processed files for native grid
filename_tail_native: '_ECCO_V4r4_native_llc0090.nc'

# String
# Absolute directory path string for the mapping factors directory
# Default: /aws/mapping_factors
mapping_factors_dir: ''

# String
# Absolute directory path string for the model output directory
# Default: /aws/temp_model_output
model_output_dir: ''

# String
# Subfolder within model_output_dir to look for model output files
model_output_dir_folder_name: 'V4r4'

# String
# Absolute directory path string for the metadata directory
# Default: /aws/metadata
metadata_dir: ''

# String
# Filename string of the PODAAC metadata to use (must be a CSV)
podaac_metadata_filename: 'PODAAC_datasets-revised_20210226.5.csv'

# String
# Absolute directory path string for the ECCO grid directory (must include all necessary grids and files)
# Default: /aws/ecco_grids
ecco_grid_dir: ''

# String
# Absolute directory path string for the ECCO grid mds directory (must include all necessary grids and files)
# Default: /aws/ecco_grids
ecco_grid_dir_mds: ''

# String
# Filename string of the ECCO grid file (must be a NetCDF4 file)
ecco_grid_filename: 'GRID_GEOMETRY_ECCO_V4r4_native_llc0090.nc'

# String
# Base absolute directory path string for the processed output files
# Default: /aws/temp_output
processed_output_dir_base: ''


# =================================================================================================
# Model Values
# =================================================================================================
# Int
binary_fill_value: -9999

# String
array_precision: 'float32'

# String
model_start_time: '1992-01-01T12:00:00'

# String
model_end_time: '2017-12-31T12:00:00'


# =================================================================================================
# Grid Values
# =================================================================================================
# Int
# Maximum number of vertical levels. Assumes only 1 vertical level for 2D files.
num_vertical_levels: 50

# Float
latlon_grid_resolution: 0.5

# Float
# Numerical value for effective grid radius for the latlon grid
# Default: 0.5*111/2*root(2)*1.1
latlon_effective_grid_radius: 

# Float
latlon_max_lat: 90.0

# List(Float)
latlon_grid_area_extent: [-180.0, 90.0, 180.0, -90.0]

# List(Float)
# Resolution independent
latlon_grid_dims: [360, 180]

# Boolean
# Sets the "read_grid" value for xmitgcm.open_mdsdataset
read_ecco_grid_for_native_load: True


# GROUPINGS
# =================================================================================================
# 20 NATIVE GRID GROUPINGS
#    0 dynamic sea surface height and model sea level anomaly
#    1 ocean bottom pressure and model ocean bottom pressure anomaly
#    2 ocean and sea-ice surface freshwater fluxes
#    3 ocean and sea-ice surface heat fluxes
#    4 atmosphere surface temperature, humidity, wind, and pressure
#    5 ocean mixed layer depth
#    6 ocean and sea-ice surface stress
#    7 sea-ice and snow concentration and thickness
#    8 sea-ice velocity
#    9 sea-ice and snow horizontal volume fluxes
#    10 Gent-McWilliams ocean bolus transport streamfunction
#    11 ocean three-dimensional volume fluxes
#    12 ocean three-dimensional potential temperature fluxes
#    13 ocean three-dimensional salinity fluxes
#    14 sea-ice salt plume fluxes
#    15 ocean potential temperature and salinity
#    16 ocean density, stratification, and hydrostatic pressure
#    17 ocean velocity
#    18 Gent-McWilliams ocean bolus velocity
#    19 ocean three-dimensional momentum tendency

# ----- > groupings_native_snap (5) = [0, 1, 7, 8, 15]
# SSH, obp, sea ice and snow, sea ice velocity, TS

# 13 LATLON GRID GROUPINGS
#    0 dynamic sea surface height
#    1 ocean bottom pressure
#    2 ocean and sea-ice surface freshwater fluxes
#    3 ocean and sea-ice surface heat fluxes
#    4 atmosphere surface temperature, humidity, wind, and pressure
#    5 ocean mixed layer depth
#    6 ocean and sea-ice surface stress
#    7 sea-ice and snow concentration and thickness
#    8 sea-ice velocity
#    9 ocean potential temperature and salinity
#    10 ocean density, stratification, and hydrostatic pressure
#    11 ocean velocity
#    12 Gent-McWilliams ocean bolus velocity