# This is the static configuration file for the ECCO document generator product; it should be provided to the user with each ECCO release
# All paths are relative to the "utilities" directory in the base document generator directory


remote_server_hostname: urs.earthdata.nasa.gov

possible_grid_types:
  - latlon
  - native
  - 1D

possible_granule_types:
  - coordinate
  - variable

table_section_titles:
  coordinate_native: "Native lat-lon-cap 90 (llc90) Coordinates and Grid Geometry"
  coordinate_latlon: "Lat-Lon Coordinates and Grid Geometry" 
  variable_native: "Native Dataset Groupings"
  variable_latlon: "Lat-Lon Dataset Groupings"
  variable_1D: "1-D Dataset Groupings"


global_attributes_json_file: document_files/v4r4/input_files_json/attribute_files/global_attributes.json
global_attributes_tex_file: document_files/v4r4/document/static/global_attributes.tex
#
variable_attributes_json_file: document_files/v4r4/input_files_json/attribute_files/variable_attributes.json
variable_attributes_tex_file: document_files/v4r4/document/static/variable_attributes.tex

example_latlon_table_tex_file: document_files/v4r4/document/user_generated/example_latlon_table.tex
example_native_table_tex_file: document_files/v4r4/document/user_generated/example_native_table.tex
example_1D_table_tex_file: document_files/v4r4/document/user_generated/example_1D_table.tex


groupings_coordinate_native_json_file: document_files/v4r4/input_files_json/wecandobetter/native_coords.json
groupings_coordinate_latlon_json_file: document_files/v4r4/input_files_json/wecandobetter/latlon_coords.json
#
groupings_variable_native_json_file: document_files/v4r4/input_files_json/groupings/ECCOv4r4_groupings_for_native_datasets.json
groupings_variable_latlon_json_file: document_files/v4r4/input_files_json/groupings/ECCOv4r4_groupings_for_latlon_datasets.json
groupings_variable_1D_json_file: document_files/v4r4/input_files_json/groupings/ECCOv4r4_groupings_for_1D_datasets.json


coordinate_files_native_dir: document_files/v4r4/granule_datasets/coordinate_files/coordinate_files_native
coordinate_files_latlon_dir: document_files/v4r4/granule_datasets/coordinate_files/coordinate_files_latlon
#
variable_files_native_dir: document_files/v4r4/granule_datasets/granule_files/granules_native
variable_files_latlon_dir: document_files/v4r4/granule_datasets/granule_files/granules_latlon
variable_files_1D_dir: document_files/v4r4/granule_datasets/granule_files/granules_1D


figures_coordinate_native_dir: document_files/v4r4/figures/figures_coordinates_native 
figures_coordinate_latlon_dir: document_files/v4r4/figures/figures_coordinates_latlon 
#
figures_variable_native_dir: document_files/v4r4/figures/figures_granules_native 
figures_variable_latlon_dir: document_files/v4r4/figures/figures_granules_latlon 
figures_variable_1D_dir: document_files/v4r4/figures/figures_granules_1D 


coordinate_table_native_tex_file: document_files/v4r4/document/user_generated/native_coords_table.tex
coordinate_table_latlon_tex_file: document_files/v4r4/document/user_generated/latlon_coords_table.tex
#
variable_table_native_tex_file: document_files/v4r4/document/user_generated/native_variables_tables.tex
variable_table_latlon_tex_file: document_files/v4r4/document/user_generated/latlon_variables_tables.tex
variable_table_1D_tex_file: document_files/v4r4/document/user_generated/1D_variables_tables.tex


global_attributes_latex_lines:
  - r'% Table 8-1 Mandatory global attributes for GDS 2.0 netCDF data files'
  - r'\begin{longtable}{|p{0.276\textwidth}|p{0.092\textwidth}|p{0.46\textwidth}|p{0.092\textwidth}|}'
  - r'\caption{Mandatory global attributes for GDS 2.0 netCDF data files}'
  - r'\label{tab:global-attributes} \\ '
  - r'\hline \endhead'
  - r'\hline \endfoot'
  - r'\rowcolor{lightgray} \textbf{Global Attribute Name} & \textbf{Type} & \textbf{Description} & \textbf{Source} \\ \hline'
#
variable_attributes_latex_lines:
  - r'% Table 8-2 Variable attributes for GDS 2.0 netCDF data files',
  - r'\begin{longtable}{|p{0.168\textwidth}|p{0.20\textwidth}|p{0.46\textwidth}|p{0.092\textwidth}|}',
  - r'\caption{Table 8-2. Variable attributes for GDS 2.0 netCDF data files}',
  - r'\label{tab:variable-attributes} \\ ',
  - r'\hline \endhead',
  - r'\hline \endfoot',
  - r'\rowcolor{lightgray} \textbf{Variable Attribute Name} & \textbf{Format} & \textbf{Description} & \textbf{Source} \\ \hline',
