# This is the static configuration file for the ECCO document generator product; it should be provided to the user with each ECCO release
# All paths are relative to the base document generator directory

# Tail string for the dataset description for latlon grid
dataset_description_tail_latlon: ' interpolated to a regular 0.5-degree grid from the ECCO Version 4 Release 6 (V4r6) ocean and sea-ice state estimate.'

# Tail string for the dataset description for native grid
dataset_description_tail_native: ' on the native Lat-Lon-Cap 90 (LLC90) model grid from the ECCO Version 4 Release 6 (V4r6) ocean and sea-ice state estimate.'

component_tex_files_to_modify_dict:
  front_pages: 
    - 'files_general/resource_files/version_specific/V4r4/input_and_templates/latex/components/front_pages_template.tex'
    - 'files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/front_pages.tex'

file_modification_commands_dict:
  front_pages: "sed \"s/REPLACE-WITH-ISSUE-DATE/$(date +%B) $(date +%d), $(date +%Y)/\" {base_dir}/{file_in} > {base_dir}/{file_out}"


thumbnail_size: 512
#thumbnail_size: 256
#thumbnail_size: 128
thumbnail_path_modifier_string: _thumbnail

tab_char: \t
tab_width_cm: 0.5

##overwrite_switch: True
overwrite_switch: False

ecco_version_string: V4r4

url_grid_type_substrings:
  - _native
  - _lat-lon
  - _1D

url_coordinate_substring: GRID_GEOMETRY

possible_grid_types:
  - lat-lon
  - native
  - 1D

possible_granule_types:
  - coordinate
  - variable

global_attribute_rowcolor: cyan!25
variable_attribute_rowcolor: violet!25


# Testing-specific entries:

granules_url_list_file_relative: files_general/resource_files/version_specific/V4r4/input_and_templates/granules_to_download_testing/granules_to_download.txt
variable_attributes_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json_testing/attribute_files/variable_attributes.json
groupings_variable_native_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json_testing/groupings/ECCOV4r4_groupings_for_native_datasets.json
groupings_variable_lat-lon_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json_testing/groupings/ECCOV4r4_groupings_for_lat-lon_datasets.json
groupings_variable_1D_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json_testing/groupings/ECCOV4r4_groupings_for_1D_datasets.json
variable_files_native_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules_testing/variable_granules/granules_native
variable_files_lat-lon_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules_testing/variable_granules/granules_lat-lon
variable_files_1D_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules_testing/variable_granules/granules_1D




# Production-specific entries:

#granules_url_list_file_relative: files_general/resource_files/version_specific/V4r4/input_and_templates/granules_to_download/granules_to_download.txt
#variable_attributes_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/attribute_files/variable_attributes.json
#groupings_variable_native_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/groupings/ECCOV4r4_groupings_for_native_datasets.json
#groupings_variable_lat-lon_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/groupings/ECCOV4r4_groupings_for_lat-lon_datasets.json
#groupings_variable_1D_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/groupings/ECCOV4r4_groupings_for_1D_datasets.json
#variable_files_native_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules/variable_granules/granules_native
#variable_files_lat-lon_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules/variable_granules/granules_lat-lon
#variable_files_1D_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules/variable_granules/granules_1D






# Universal entries:

global_attributes_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/attribute_files/global_attributes.json
global_attributes_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/global_attributes.tex

variable_attributes_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/variable_attributes.tex

example_lat-lon_table_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/example_lat-lon_table.tex
example_native_table_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/example_native_table.tex
example_1D_table_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/example_1D_table.tex

groupings_coordinate_native_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/wecandobetter/native_coords.json
groupings_coordinate_lat-lon_json_file: files_general/resource_files/version_specific/V4r4/input_and_templates/json/wecandobetter/lat-lon_coords.json

coordinate_files_native_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules/coordinate_granules/granules_native
coordinate_files_lat-lon_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/granules/coordinate_granules/granules_lat-lon

figures_coordinate_native_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/output/figures/figures_coordinates_native 
figures_coordinate_lat-lon_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/output/figures/figures_coordinates_lat-lon 

figures_variable_native_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/output/figures/figures_variables_native 
figures_variable_lat-lon_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/output/figures/figures_variables_lat-lon 
figures_variable_1D_dir: files_general/resource_files/version_specific/V4r4/output_and_granules/output/figures/figures_variables_1D 


coordinate_table_native_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/native_coords_table.tex
coordinate_table_lat-lon_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/lat-lon_coords_table.tex

variable_table_native_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/native_variables_tables.tex
variable_table_lat-lon_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/lat-lon_variables_tables.tex
variable_table_1D_tex_file: files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex/1D_variables_tables.tex

example_granule_1D: GLOBAL_MEAN_ATM_SURFACE_PRES_snap_ECCO_V4r4_1D.nc
example_granule_lat-lon: SEA_SURFACE_HEIGHT_day_mean_2017-12-29_ECCO_V4r4_latlon_0p50deg.nc
example_granule_native: OCEAN_TEMPERATURE_SALINITY_day_mean_2017-12-29_ECCO_V4r4_native_llc0090.nc


table_section_titles:
  coordinate_native: "Native lat-lon-cap 90 (llc90) Coordinates and Grid Geometry"
  coordinate_lat-lon: "Lat-Lon Coordinates and Grid Geometry" 
  variable_native: "Native Dataset Groupings"
  variable_lat-lon: "Lat-Lon Dataset Groupings"
  variable_1D: "1-D Dataset Groupings"

global_attributes_latex_lines:
  - \begin{longtable}{|p{0.276\textwidth}|p{0.092\textwidth}|p{0.46\textwidth}|p{0.092\textwidth}|}
  - \caption{Mandatory global attributes for GDS 2.0 netCDF data files}
  - \label{tab:global-attributes} \\ 
  - \hline \endfirsthead \endhead \endfoot \hline \endlastfoot
  - \rowcolor{blue!25} \textbf{Global Attribute Name} & \textbf{Type} & \textbf{Description} & \textbf{Source} \\ \hline
  #- \rowcolor{lightgray} \textbf{Global Attribute Name} & \textbf{Type} & \textbf{Description} & \textbf{Source} \\ \hline
#
variable_attributes_latex_lines:
  - \begin{longtable}{|p{0.168\textwidth}|p{0.20\textwidth}|p{0.46\textwidth}|p{0.092\textwidth}|}
  - \caption{Coordinte, Dimension, and Variable attributes for GDS 2.0 netCDF data files}
  #- \caption{Variable attributes for GDS 2.0 netCDF data files}
  - \label{tab:variable-attributes} \\ 
  - \hline \endfirsthead \endhead \endfoot \hline \endlastfoot
  - \rowcolor{blue!25} \textbf{Variable Attribute Name} & \textbf{Format} & \textbf{Description} & \textbf{Source} \\ \hline
  #- \rowcolor{lightgray} \textbf{Variable Attribute Name} & \textbf{Format} & \textbf{Description} & \textbf{Source} \\ \hline

example_table_first_latex_lines_lat-lon:
  #- \caption{Example CDL description of lat-lon dataset}
  - \caption{Example Common Data format Language (CDL) description of lat-lon dataset}
  - \label{tab:cdl-lat-lon} \\
  - \hline \endfirsthead \endhead \endfoot \hline \endlastfoot

example_table_first_latex_lines_native:
  #- \caption{Example CDL description of native dataset}
  - \caption{Example Common Data format Language (CDL) description of native dataset}
  - \label{tab:cdl-native} \\
  - \hline \endfirsthead \endhead \endfoot \hline \endlastfoot

example_table_first_latex_lines_1D:
  #- \caption{Example CDL description of 1D dataset}
  - \caption{Example Common Data format Language (CDL) description of 1D dataset}
  - \label{tab:cdl-1D} \\
  - \hline \endfirsthead \endhead \endfoot \hline \endlastfoot

longtable_headers_footers: \hline \endfirsthead \endhead \endfoot \hline \endlastfoot

# -----------------------------------------------------------------------------------------------------------------------------------
compendium_compilation_runtime_message_string: |+
  
  Compiling the final latex document (if successful, will be found in the directory 'final_compendium_files')
  
  Note: 'pdflatex' is running in the background; if execution seems stalled, try typing "X" and pressing Enter. If this works, 
  useful error messages should print to the screen.  Otherwise, terminate the process (e.g. type'ctrl + c' and hit 'return'), 
  and look for error messages in the '__.log' file, which should be found in the 'final_compendium_files' directory.

dummy_entry_to_set_number_of_blank_lines_at_the_end_of_the_above_message: blah
# -----------------------------------------------------------------------------------------------------------------------------------

final_compendium_files_dir: "files_general/compendium_compilation_output_files"
compendium_tex_filepath: "files_general/resource_files/version_specific/V4r4/input_and_templates/latex/main_compendium_template_DO_NOT_MODIFY/ECCO_V4r4_Dataset_Catalog_and_Variable_Compendium.tex"
static_support_tex_dir_relative: "files_general/resource_files/version_specific/V4r4/input_and_templates/latex/components"
user_generated_tex_dir_relative: "files_general/resource_files/version_specific/V4r4/output_and_granules/output/latex"
user_generated_granules_dir_relative: "files_general/resource_files/version_specific/V4r4/output_and_granules/granules"

remote_server_hostname: urs.earthdata.nasa.gov
