# aws_config.yaml
# =================================================================================================
# Contains values that are specific to AWS processing (AWS S3/AWS Lambda)
# This includes AWS paths and names, job control values, and Lambda function values
# SOME VALUES ARE SPECIFIC TO EACH VERSION, SO ENSURE VALUES ARE ACCURATE FOR ECCO VERSION


# String
# AWS Account ID
account_id: '448078824696'


# =================================================================================================
# CREDENTIALS VALUES
# =================================================================================================
# String
# Name of AWS Credential profile to use for authentication
profile_name: 'saml-pub'

# String
# AWS region to use
region: 'us-west-2'

# String
# Method to use for updating credentials (either 'binary', or 'python')
credential_method_type: 'python'

# String
# Path to AWS credential updating file (default = ECCO-Dataset-Production/aws/src/utils/aws_login/update_AWS_cred_ecco_production.sh for bash,
# and ECCO-Dataset-Production/aws/src/utils/aws_login/aws-login.{darwin/linux}.amd64 for binary)
aws_credentials_bash_filepath: ''


# =================================================================================================
# S3 VALUES
# =================================================================================================
# String
# Name of S3 bucket to source ECCO model output files
source_bucket: 'ecco-model-granules'

# String
# Subfolder of source_bucket to source ECCO model output files
bucket_subfolder: 'V4r4'

# String
# Name of S3 bucket to save processed datasets
output_bucket: 'ecco-processed-data'

# String
# Name of S3 bucket to use for testing purposes
test_bucket: 'ecco-test-lambda'


# =================================================================================================
# LAMBDA VALUES
# =================================================================================================
# String
# URI of Docker image to use from AWS Elastic Container Registry (ECR)
image_uri: '448078824696.dkr.ecr.us-west-2.amazonaws.com/ecco_processing:latest'

# String
# Name of the role for the lambda's to assume when executing
role: 'lambda-role'

# String
# Lambda function name prefix (2D/3D_native/latlon appended)
function_name_prefix: 'ecco_processing'


# =================================================================================================
# JOB SETUP AND CONTROL (EXECUTION TIMES, MAX EXECS, TIMEOUT, and RETRY)
# =================================================================================================
# Boolean
# Controls whether or not to invoke each lambda job in parallel
use_workers_to_invoke: True

# Float
# Time to process single 2D latlon vertical level (s)
latlon_2D_time: 0.5

# Float
# Time to process single 3D latlon vertical level (s)
latlon_3D_time: 0.075

# Float
# Time to process single 2D native vertical level (s)
native_2D_time: 0.8

# Float
# Time to process single 3D native vertical level (s)
native_3D_time: 0.05

# Int
# Override the max number of timestep executions to be processed in each lambda job.
# This value is used if lower than the calculated max_execs from time.
# This value will be ignored if set to 0.
override_max_execs: 0

# Float
# Timeout (in seconds) for each job. Lambda has a timeout of 900s, this value
# will stop the job and print out necessary logging information, so it should be less than 900s.
job_timeout: 890.0

# Int
# Number of times to retry processing a failed timestep
num_retry: 1


# =================================================================================================
# LAMBDA FUNCTION MEMORY SIZES (2D/3D latlon and 2D/3D native)
# =================================================================================================
# Int
# Memory size for 2D latlon lambda jobs (MB)
memory_size_2D_latlon: 1024

# Int
# Memory size for 3D latlon lambda jobs (MB)
memory_size_3D_latlon: 1536

# Int
# Memory size for 2D native lambda jobs (MB)
memory_size_2D_native: 1536

# Int
# Memory size for 3D native lambda jobs (MB)
memory_size_3D_native: 1536

# Int
# Number of batches to process. Overrides calculated value if lower
number_of_batches_to_process: 100000